# src/main/resources/application.yml
grpc:
  client:
    local-grpc-server:
      address: 'static://localhost:9090'
      enableKeepAlive: true
      negotiationType: plaintext # ?? ????? ??, ?? ????? TLS ??
      # Keepalive ??:
      # ?????? ??? Keepalive Ping? ??? ?? ???? ??.
      # 10??? Ping? ?? ??? ?? ???? ??? ????.
#      keepAliveTime: 10s
      # Keepalive Ping ?? ?? ??.
      # Ping? ?? ? 5? ?? ??? ??? ??? ?????.
#      keepAliveTimeout: 5s
      # ??? ?? ???(RPC)? ?? ?? Keepalive Ping? ??? ??.
      # true? ???? ?? ????? Ping? ?? ??? ?????.
#      keepAliveWithoutCalls: true